# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

builds:
  - id: client-go
    dir: packages/client-go
    binary: open-xiaoai-client-go
    main: ./cmd/client/
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    goos:
      - linux
    goarch:
      - arm64
      - arm
    goarm:
      - "5"
      - "6"
      - "7"
      
  - id: gemini-go
    dir: examples/gemini-go
    binary: gemini-go
    main: .
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
  - id: gpt-go
    dir: examples/gpt-go
    binary: gpt-go
    main: .
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

upx:
  - ids: [client-go, gemini-go, gpt-go]
    enabled: true
    
archives:
  - id: client-go
    builds: [client-go]
    formats: [tar.gz]
    name_template: >-
      open-xiaoai-client-go_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
  - id: gemini-go
    builds: [gemini-go]
    formats: [tar.gz]
    name_template: >-
      gemini-go_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]
  - id: gpt-go
    builds: [gpt-go]
    formats: [tar.gz]
    name_template: >-
      gpt-go_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  draft: true
  replace_existing_draft: true
  prerelease: auto
  name_template: "{{.ProjectName}}-v{{.Version}}-{{.Date}}"
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).